project:
  type: website

website:
  title: "Bernat Puig Camps"
  favicon: profile.jpg
  navbar:
    menu: false
    logo: "profile.jpg"
    title: "Bernat Puig Camps"
    # right:
    #   - icon: linkedin
    #     href: https://linkedin.com/in/bepuca/
    #   - icon: github
    #     href: https://github.com/bepuca

format:
  html:
    theme:
      light: [default, theme.scss]
      dark: [default, theme-dark.scss]
    highlight-style: ayu
    css: styles.css

resources:
  - CNAME
